name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "Current directory before cd:"
          pwd
          cd /home/ruslan/telegramtetrisblitz.ru/app || { echo "Directory not found!"; exit 1; }
          echo "Changed directory to:"
          pwd
          echo "Pulling latest changes..."
          git pull origin main
          echo "Installing npm dependencies..."
          npm install
          echo "Restarting or starting pm2 process..."
          pm2 restart telegram-tetris || pm2 start node_modules/.bin/live-server --name telegram-tetris -- public
          echo "Deployment finished."
