name: Deploy to VPS

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/telegramtetrisblitz.ru/app
          git pull origin main
          npm install
          pm2 restart telegram-tetris || pm2 start node_modules/.bin/live-server --name telegram-tetris -- public
